### ISSUE TITLE
Body Size does not update in `Responsive Mode` in Chrome

### ISSUE THREAD

**Issue by DeBraid** [ladieslearningcode/llc-responsive-design#3]
EDIT 2: OOOOPS, it's in the slide deck at `ladies-learning-code/llc-responsive-design/slides.html#slide63`

Closing.

EDIT 1: 
appears to be part of known bug --> http://stackoverflow.com/questions/26888751/chrome-device-mode-emulation-media-queries-not-working

# Solution 
While the `index.html` does include a comment regarding this fix, 
add: 
`<meta name="viewport" content="width=device-width">`
Going over instructions in `ladies-learning-code/llc-responsive-design/slides.html#slide59`

When the DevTools are open, and running in `Responsive` mode sets the `body` width to `980px` regardless of the mode. 

## To recreate

1.  Set mode to Responsive
2.  Go to Mobile S (320px width)
3.  Inspect the `body` to observe `width`.

However, if the DevTools are closed, and a user manually adjusts the Browser window size, the media queries work!  Something is up with the DevTools config. 

## Proposed Solution 

* Add something in the devtools to detect resize events (??)

Perhaps the internals have changed in Chrome causing the body to NOT adjust?  One can manually resize the browser and observe the changes via media queries.

**Comment by DeBraid** [comment]
Solution is in the slide deck, caught it too late. `ladies-learning-code/llc-responsive-design/slides.html#slide63`

**Comment by DeBraid** [comment]
Perhaps move slide 63 before the exercise on slide 58 to avoid other sessions bumping into this issue.

**Comment by kasslent** [comment]
Thanks for the suggestion! We'll keep it in mind, as we're in the process of updating.
